import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { ShoppingCartProvider } from "@/context/ShoppingCartContext";

const vazirmatn = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Salar ECommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ShoppingCartProvider>
        <body className={vazirmatn.className}>
          <Navbar />
          {children}
        </body>
      </ShoppingCartProvider>
    </html>
  );
}
